import scrapy


class QuotesSpider(scrapy.Spider):
    """Creates a spider that will crawl and scrape your named urls.
    name is the name of your spider. It must be unique."""

    name = "quotes"

    start_urls = [
        'http://quotes.toscrape.com/page/1/',
        'http://quotes.toscrape.com/page/2/',
    ]

    def parse(self, response):
        """Parses the response object and extracts data as dicts.
        Saves the response body in a txt file.
        Name of txt file is generated by the page number in the url.
        Parse is Scrapy's default callback method.
        It will be called for requests even without an explicity assigned callback."""
        page = response.url.split("/")[-2]
        filename = 'quotes-{}.html'.format(page)
        with open(filename, 'wb') as f:
            f.write(response.body)
        self.log("Saved file {}".format(filename))
